# Example Application Configuration
# Copy this file to config.yaml and adjust as needed
# This file contains non-sensitive settings
# Credentials should be set in .env file or environment variables

# Knowledge Base Settings
KB_PATH: ./knowledge_base
KB_GIT_ENABLED: true
KB_GIT_AUTO_PUSH: true
KB_GIT_REMOTE: origin
KB_GIT_BRANCH: main

# Processing Settings
MESSAGE_GROUP_TIMEOUT: 30  # seconds
PROCESSED_LOG_PATH: ./data/processed.json

# Logging Settings
LOG_LEVEL: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_FILE: ./logs/bot.log

# User Access Control
# Comma-separated list of allowed Telegram user IDs
# Empty string means all users are allowed
# Example: "123456789,987654321"
ALLOWED_USER_IDS: ""

# Agent Configuration
AGENT_TYPE: "qwen_code_cli"  # Options: stub, qwen_code, qwen_code_cli (recommended)
AGENT_MODEL: "qwen-max"  # Model for Qwen agent (for qwen_code type)
AGENT_QWEN_CLI_PATH: "qwen"  # Path to qwen CLI (for qwen_code_cli type)
AGENT_TIMEOUT: 300  # Timeout in seconds for agent operations
AGENT_ENABLE_WEB_SEARCH: true
AGENT_ENABLE_GIT: true
AGENT_ENABLE_GITHUB: true
AGENT_ENABLE_SHELL: false  # Security risk - keep disabled
