# Docker Compose for MLX backend (macOS Apple Silicon)
# Use this for running on macOS with Apple Silicon (M1/M2/M3)
#
# Note: MLX requires macOS with Apple Silicon
# This setup runs the MLX server directly on the host (not in Docker)
# 
# Usage:
#   1. Install MLX on macOS: pip install mlx mlx-lm
#   2. Start MLX server manually:
#      python -m mlx_lm.server --model ${MEM_AGENT_MODEL} --port 8001
#   3. Start other services:
#      docker-compose -f docker-compose.yml -f docker-compose.mlx.yml up -d
# Or:
#   make up-mlx

version: '3.8'

services:
  # MLX server (containerized) – CPU-only images available, but MLX
  # officially targets macOS; for Linux we'll keep host-run mode as default.
  # If you have a working container, set MEM_AGENT_BACKEND=mlx and use it.
  mlx-server:
    image: ghcr.io/ml-explore/mlx-lm:latest
    container_name: tg-note-mlx
    command: >
      python -m mlx_lm.server --model ${MEM_AGENT_MODEL:-driaforall/mem-agent} --port 8001
    ports:
      - "${MLX_PORT:-8001}:8001"
    environment:
      - HF_HOME=/root/.cache/huggingface
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - tg-note-network

  # Disable vLLM when using MLX override
  vllm-server:
    profiles:
      - disabled

  # Update mcp-hub to connect to mlx-server
  mcp-hub:
    environment:
      - MEM_AGENT_BACKEND=mlx
      - MEM_AGENT_HOST=mlx-server
      - MEM_AGENT_PORT=8001
      # Base URL is constructed internally
    depends_on:
      mlx-server:
        condition: service_healthy

  # Bot depends on mcp-hub
  bot:
    depends_on:
      mcp-hub:
        condition: service_healthy
