site_name: tg-note Documentation
site_description: Intelligent Knowledge Base Builder - Telegram bot documentation
site_author: Artem Zemliak
site_url: https://artyomzemlyak.github.io/tg-note/

repo_name: ArtyomZemlyak/tg-note
repo_url: https://github.com/ArtyomZemlyak/tg-note
edit_uri: edit/main/docs_site/

docs_dir: docs_site


theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
    # Palette toggle for dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  features:
  - navigation.instant
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.top
  - navigation.footer
  - search.suggest
  - search.highlight
  - search.share
  - toc.follow
  - content.code.copy
  - content.code.annotate
  - content.tabs.link

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
- admonition
- pymdownx.details
- pymdownx.tasklist:
    custom_checkbox: true
- attr_list
- md_in_html
- toc:
    permalink: true

plugins:
- search
- tags

extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/ArtyomZemlyak/tg-note
    name: GitHub Repository
  version:
    provider: mike

nav:
- Home: index.md

- Getting Started:
  - Quick Start: getting-started/quick-start.md
  - Installation: getting-started/installation.md
  - Configuration: getting-started/configuration.md
  - First Steps: getting-started/first-steps.md

- User Guide:
  - Bot Commands: user-guide/bot-commands.md
  - Working with Content: user-guide/working-with-content.md
  - Settings Management: user-guide/settings-management.md
  - MCP Server Management: user-guide/mcp-server-management.md
  - File Format Recognition: user-guide/file-format-recognition.md
  - Knowledge Base Setup: user-guide/knowledge-base-setup.md

- Agent System:
  - Overview: agents/overview.md
  - Qwen Code CLI: agents/qwen-code-cli.md
  - Qwen CLI Debug Trace: agents/qwen-cli-debug-trace.md
  - Autonomous Agent: agents/autonomous-agent.md
  - Stub Agent: agents/stub-agent.md
  - MCP Tools:
    - MCP Tools Overview: agents/mcp-tools.md
    - Memory Agent Setup: agents/mem-agent-setup.md
    - MCP Server Registry: agents/mcp-server-registry.md
    - MCP Config Format: agents/mcp-config-format.md
    - KB Reading Tools: agents/kb-reading-tools.md

- Architecture:
  - System Overview: architecture/overview.md
  - Agent Architecture: architecture/agent-architecture.md
  - Settings System: architecture/settings-architecture.md
  - Data Flow: architecture/data-flow.md
  - Storage Paths: architecture/storage-paths.md
  - KB Synchronization: architecture/kb-synchronization.md
  - MCP Architecture: architecture/mcp-architecture.md
  - Message DTO: architecture/message-dto.md

- Development:
  - Overview: development/overview.md
  - Project Structure: development/project-structure.md
  - Running Tests: development/testing.md
  - Code Quality: development/code-quality.md
  - Contributing: development/contributing.md

- Deployment:
  - Overview: deployment/overview.md
  - Production Checklist: deployment/production.md
  - Docker: deployment/docker.md
  - Vector Search Stack: deployment/docker-vector-search.md
  - CI/CD: deployment/cicd.md
  - PyPI Trusted Publisher: deployment/pypi-trusted-publisher-setup.md
  - Auto Deploy (Cron): deployment/auto-deploy.md

- Reference:
  - Overview: reference/overview.md
  - Configuration Options: reference/configuration.md
  - API Documentation: reference/api.md
  - Git Operations: reference/git-operations.md
  - Troubleshooting: reference/troubleshooting.md
  - FAQ: reference/faq.md

copyright: Copyright &copy; 2025 Artem Zemliak
